openapi: 3.0.0
info:
  version: 1.0.0
  title: Test for mock-server.com
paths:
  /test-objects:
    get:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/testObject'
        '409':
          description: Conflict
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Conflict'
components:
  schemas:
    testObject:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        fullTime:
          type: boolean
      example:
        id: 1
        name: Jessica Right
        fullTime: true
    Conflict:
     type: object
     properties:
        id:
          type: integer
        name:
          type: string
        fullTime:
          type: boolean
     example:
        id: 1
        name: Jessica Right
        fullTime: true
